# Generated by Django 5.0.3 on 2024-04-25 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_identification'),
        ('patients_images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient_Image',
            new_name='Patientimage',
        ),
        migrations.AlterModelOptions(
            name='patientimage',
            options={'verbose_name': 'PatientImage', 'verbose_name_plural': 'PatientImages'},
        ),
    ]
