# Generated by Django 5.0.3 on 2024-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_images', '0002_rename_patient_image_patientimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='front',
            field=models.ImageField(default='patients_profile/front/default_image.jpeg', upload_to='patients_profile/front', verbose_name='foto_frontal'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='front_intraoral',
            field=models.ImageField(default='patients_profile/front_intraoral/default_image.jpeg', upload_to='patients_profile/front_intraoral', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='front_smiling',
            field=models.ImageField(default='patients_profile/front_smiling/default_image.jpeg', upload_to='patients_profile/front_smiling', verbose_name='frontal_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='left_side',
            field=models.ImageField(default='patients_profile/left_side/default_image.jpeg', upload_to='patients_profile/left_side', verbose_name='lateral_izquierda'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='left_side_smiling',
            field=models.ImageField(default='patients_profile/left_side_smiling/default_image.jpeg', upload_to='patients_profile/left_side_smiling', verbose_name='lateral_izquierda_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='lower_oclusal',
            field=models.ImageField(default='patients_profile/lower_oclusal/default_image.jpeg', upload_to='patients_profile/lower_oclusal', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='right_side',
            field=models.ImageField(default='patients_profile/rigth_side/default_image.jpeg', upload_to='patients_profile/rigth_side', verbose_name='lateral_derecha'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='right_side_smiling',
            field=models.ImageField(default='patients_profile/right_side_smiling/default_image.jpeg', upload_to='patients_profile/right_side_smiling', verbose_name='lateral_derecha_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='upper_oclusal',
            field=models.ImageField(default='patients_profile/upper_oclusal/default_image.jpeg', upload_to='patients_profile/upper_oclusal', verbose_name='oclusal_superior'),
        ),
    ]
