# Generated by Django 5.0.7 on 2024-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_images', '0003_alter_patientimage_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='extra_photo1',
            field=models.ImageField(default='patients_profile/extra_photo1/default_image.jpeg', max_length=255, upload_to='patients_profile/extra_photo1', verbose_name='imagen_extra1'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='extra_photo2',
            field=models.ImageField(default='patients_profile/extra_photo2/default_image.jpeg', max_length=255, upload_to='patients_profile/extra_photo2', verbose_name='imagen_extra1'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='front',
            field=models.ImageField(default='patients_profile/front/default_image.jpeg', max_length=255, upload_to='patients_profile/front', verbose_name='foto_frontal'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='front_intraoral',
            field=models.ImageField(default='patients_profile/front_intraoral/default_image.jpeg', max_length=255, upload_to='patients_profile/front_intraoral', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='front_smiling',
            field=models.ImageField(default='patients_profile/front_smiling/default_image.jpeg', max_length=255, upload_to='patients_profile/front_smiling', verbose_name='frontal_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='lateral_xray',
            field=models.ImageField(default='patients_profile/lateral_xray/default_image.jpeg', max_length=255, upload_to='patients_profile/lateral_xray', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='left_side',
            field=models.ImageField(default='patients_profile/left_side/default_image.jpeg', max_length=255, upload_to='patients_profile/left_side', verbose_name='lateral_izquierda'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='left_side_intraoral',
            field=models.ImageField(default='patients_profile/right_side_intraoral/default_image.jpeg', max_length=255, upload_to='patients_profile/right_side_intraoral', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='left_side_smiling',
            field=models.ImageField(default='patients_profile/left_side_smiling/default_image.jpeg', max_length=255, upload_to='patients_profile/left_side_smiling', verbose_name='lateral_izquierda_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='lower_oclusal',
            field=models.ImageField(default='patients_profile/lower_oclusal/default_image.jpeg', max_length=255, upload_to='patients_profile/lower_oclusal', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='panoramic_xray',
            field=models.ImageField(default='patients_profile/panoramic_xray/default_image.jpeg', max_length=255, upload_to='patients_profile/panoramic_xray', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='right_side',
            field=models.ImageField(default='patients_profile/rigth_side/default_image.jpeg', max_length=255, upload_to='patients_profile/rigth_side', verbose_name='lateral_derecha'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='right_side_intraoral',
            field=models.ImageField(default='patients_profile/right_side_intraoral/default_image.jpeg', max_length=255, upload_to='patients_profile/right_side_intraoral', verbose_name='oclusal_inferior'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='right_side_smiling',
            field=models.ImageField(default='patients_profile/right_side_smiling/default_image.jpeg', max_length=255, upload_to='patients_profile/right_side_smiling', verbose_name='lateral_derecha_sonriendo'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='upper_oclusal',
            field=models.ImageField(default='patients_profile/upper_oclusal/default_image.jpeg', max_length=255, upload_to='patients_profile/upper_oclusal', verbose_name='oclusal_superior'),
        ),
    ]
