version: '1.29.2'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .core/env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn


volumes:
  static:



# version: "3.3"

# services:
#   db:
#     image: postgres:13-alpine
#     container_name: database
#     restart: always
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password123
#     volumes:
#       - /var/lib/postgresql/data
#     ports:
#       - 5432:5432
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgAdmin
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
#       PGADMIN_DEFAULT_PASSWORD: password123
#       PGADMIN_LISTEN_PORT: 80
#     ports:
#       - 8080:80
#     volumes:
#       - /var/lib/pgadmin
#     depends_on:
#       - db

# volumes:
#   postgres_data:
#   pgadmin_data: