# Generated by Django 5.0.3 on 2024-04-28 02:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='nombre_paciente')),
                ('date_appointment', models.DateField(blank=True, default=datetime.date.today, verbose_name='fecha_consulta')),
                ('hour_appointment', models.TimeField(blank=True, default=None, null=True, verbose_name='hora_consulta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-date_appointment'],
            },
        ),
    ]
