# Generated by Django 5.0.3 on 2024-04-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vital_signs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.vital_sign', verbose_name='signos_vitales'),
            preserve_default=False,
        ),
    ]
