# Generated by Django 5.0.3 on 2024-04-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='vital_signs',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='appointment.vital_sign'),
        ),
    ]
