# Generated by Django 5.0.3 on 2024-04-22 03:17

import appointment.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patients', '0002_alter_patient_options_remove_patient_lastname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='treatment',
        ),
        migrations.DeleteModel(
            name='Vital_sign',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_generated',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha_cita_medica'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_pressure',
            field=models.CharField(blank=True, default=0, max_length=7, verbose_name='presion_arterial'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='breathing_frequency',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_respiratoria'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cie10_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='codigo_cie_10_odontologico'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnoses',
            field=models.TextField(blank=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnoses_complications',
            field=models.TextField(blank=True, verbose_name='diagnostico_complicaciones'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('PRE', 'presuntivo'), ('DEF', 'definitivo')], max_length=25, verbose_name='diagnostico_tipo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_cardiaca'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='oxygen_saturation',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='saturacion_oxigeno'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescriptions',
            field=models.TextField(blank=True, verbose_name='prescripciones'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedures',
            field=models.TextField(blank=True, verbose_name='procedimientos'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='temperature',
            field=appointment.models.PositiveDecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='temperatura'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
