# Generated by Django 5.0.3 on 2024-04-14 18:56

import appointment.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patients', '0002_alter_patient_options_remove_patient_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, default=0, max_length=7, verbose_name='presion_arterial')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_cardiaca')),
                ('temperature', appointment.models.PositiveDecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='temperatura')),
                ('breathing_frequency', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_respiratoria')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='saturacion_oxigeno')),
            ],
            options={
                'verbose_name': 'Vital_sign',
                'verbose_name_plural': 'Vital_signs',
            },
        ),
        migrations.DeleteModel(
            name='Vital_sign',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_generated',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha_cita_medica'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='paciente_cita'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cie10_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='codigo_cie_10_odontologico'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, verbose_name='diagnostico_descripcion'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('PRE', 'presuntivo'), ('DEF', 'definitivo')], max_length=25, verbose_name='diagnostico_tipo'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='complications',
            field=models.TextField(blank=True, verbose_name='complicaciones'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnoses',
            field=models.TextField(blank=True, verbose_name='diagnostico'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prescriptions',
            field=models.TextField(blank=True, verbose_name='prescripciones'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedures',
            field=models.TextField(blank=True, verbose_name='procedimientos'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vital_signs',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.vital_signs'),
        ),
    ]
