# Generated by Django 5.0.3 on 2024-04-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patients', '0002_alter_patient_options_remove_patient_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, default=0, max_length=7, verbose_name='presion_arterial')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_cardiaca')),
                ('breathing_frequency', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='frecuencia_respiratoria')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='saturacion_oxigeno')),
            ],
            options={
                'verbose_name': 'Vital_sign',
                'verbose_name_plural': 'Vital_signs',
            },
        ),
        migrations.DeleteModel(
            name='Vital_sign',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='diagnoses',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='appointment',
            field=models.OneToOneField(default=123456, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='appointment',
            field=models.OneToOneField(default=67890, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cie10_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='codigo_cie_10_odontologico'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('PRE', 'presuntivo'), ('DEF', 'definitivo')], max_length=25, verbose_name='diagnostico_tipo'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='complications',
            field=models.TextField(blank=True, verbose_name='complicaciones'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prescriptions',
            field=models.TextField(blank=True, verbose_name='prescripciones'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedures',
            field=models.TextField(blank=True, verbose_name='procedimientos'),
        ),
        migrations.AddField(
            model_name='vital_signs',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
