# Generated by Django 5.0.3 on 2024-04-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_appointment_vital_signs'),
        ('doctors', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.profile', verbose_name='doctor_cita'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(choices=[('PRE', 'presuntivo'), ('DEF', 'definitivo')], max_length=25, verbose_name='diagnostico_tipo'),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='blood_pressure',
            field=models.CharField(default=0, max_length=7, verbose_name='presion_arterial'),
        ),
    ]
