# Generated by Django 5.0.7 on 2024-08-12 05:49

import appointment.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='blood_pressure',
            field=models.CharField(blank=True, default=0, max_length=7, null=True, verbose_name='presion_arterial'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='breathing_frequency',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='frecuencia_respiratoria'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cie10_code',
            field=models.CharField(blank=True, default='Z012', max_length=6, verbose_name='codigo_cie_10_odontologico'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnoses',
            field=models.TextField(blank=True, default='Examen odontológico', verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnoses_complications',
            field=models.TextField(blank=True, null=True, verbose_name='diagnostico_complicaciones'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('PRE', 'presuntivo'), ('DEF', 'definitivo')], default='PRE', max_length=25, verbose_name='diagnostico_tipo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='frecuencia_cardiaca'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='oxygen_saturation',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='saturacion_oxigeno'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescriptions',
            field=models.TextField(blank=True, null=True, verbose_name='prescripciones'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedures',
            field=models.TextField(blank=True, null=True, verbose_name='procedimientos'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='temperature',
            field=appointment.models.PositiveDecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='temperatura'),
        ),
    ]
