# Generated by Django 5.0.3 on 2024-04-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_treatment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_generated',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha_cita_medica'),
        ),
    ]
