# Generated by Django 5.0.3 on 2024-04-19 23:01

import appointment.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_appointment_date_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='temperature',
            field=appointment.models.PositiveDecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='temperatura'),
        ),
    ]
