# Generated by Django 5.0.3 on 2024-04-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_diagnoses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='complications',
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnoses_complications',
            field=models.TextField(blank=True, verbose_name='diagnostico_complicaciones'),
        ),
    ]
