# Generated by Django 5.0.3 on 2024-04-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, verbose_name='correo_paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.TextField(max_length=10, unique=True, verbose_name='cedula_identidad'),
        ),
    ]
