# Generated by Django 5.0.3 on 2024-04-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_remove_patient_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='pregnant',
            field=models.BooleanField(default=False, verbose_name='embarazo'),
        ),
    ]
