# Generated by Django 5.0.3 on 2024-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, verbose_name='correo_paciente'),
        ),
    ]
