# Generated by Django 5.0.3 on 2024-04-17 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options_alter_medical_history_pregnant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_history',
            name='pregnant',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='aditional_info',
            field=models.TextField(blank=True, verbose_name='observaciones_adicionales'),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha_creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_history',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha_actualizacion'),
        ),
    ]
