# Generated by Django 5.0.3 on 2024-04-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_user_alter_patient_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='user',
        ),
    ]
