# Generated by Django 5.0.3 on 2024-04-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_medical_history_pregnant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='aditional_info',
            new_name='additional_info',
        ),
    ]
