# Generated by Django 5.0.3 on 2024-04-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_doctor_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.TextField(blank=True, max_length=10, verbose_name='cedula_identidad'),
        ),
    ]
