services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: thedoctorsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: thedoctors@outlook.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8085:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgres_data:
  pgadmin_data: