# Generated by Django 5.0.3 on 2024-04-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(db_column='id', default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='usuario_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(verbose_name='direccion_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(verbose_name='fecha_nacimiento_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='identification',
            field=models.TextField(max_length=10, unique=True, verbose_name='cedula_identidad_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(max_length=150, verbose_name='apellidos_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nombres_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='telefono_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='profile.png', upload_to='user_profile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registryCode',
            field=models.CharField(max_length=20, verbose_name='codigo_registro_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha_actualizacion_doctor'),
        ),
    ]
