# Generated by Django 5.0.3 on 2024-04-10 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=50, verbose_name='nombres_doctor')),
                ('last_names', models.CharField(max_length=50, verbose_name='apellido_doctor')),
                ('birthDate', models.DateField(default=datetime.date.today, verbose_name='fecha_nacimiento_doctor')),
                ('identification', models.CharField(max_length=15, verbose_name='cedula_identidad_doctor')),
                ('registryCode', models.CharField(max_length=20, verbose_name='codigo_registro_doctor')),
                ('address', models.CharField(max_length=200, verbose_name='direccion_doctor')),
                ('phone', models.CharField(max_length=15, verbose_name='telefono_doctor')),
                ('photo', models.ImageField(default='profile.png', upload_to='user_profile')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion_doctor')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha_actualizacion_doctor')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
