# Generated by Django 5.0.3 on 2024-04-08 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_id_doctor_user_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha_nacimiento_doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='identification',
            field=models.TextField(max_length=10, verbose_name='cedula_identidad_doctor'),
        ),
    ]
