# Generated by Django 5.0.3 on 2024-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_remove_doctor_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, default='user_specialty', max_length=50, verbose_name='especialidad'),
        ),
    ]
